finances/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myfinance.urls')),
]

myfinance/urls.py
from django.urls import path

from .views import indexView as iv
from .views import despesaView as dv
from .views import receitaView as rv
from .views import relatorioView as relv
from .views import loginView as lg
from .views import userView as us

urlpatterns = [
    path('', iv.index, name="index"),

    path('despesa/', dv.despesa, name="despesa"),
    path('despesa/<int:id_despesa>/', dv.despesaOp, name="despesaOp"),

    path('receita/', rv.receita, name="receita"),
    path('receita/<int:id_receita>/', rv.receitaOp, name="receitaOp"),

    path('relatorio/despesas', relv.despesas, name="relatorio_despesas"),
    path('relatorio/despesas/filtro', relv.despesasFiltro, name="relatorio_despesas_filtro"),
    path('relatorio/receitas', relv.receitas, name="relatorio_receitas"),
    path('relatorio/receitas/filtro', relv.receitasFiltro, name="relatorio_receitas_filtro"),

    path('login/', lg.login, name="login"),

    path('user/', us.user, name="user"),
    path('user/create/', us.userCreateExterno, name="userCreateExterno"),
    path('user/<int:id_user>/', us.userOp, name="userOp"),

]

myfinance/models.py
from django.db import models

# Create your models here.

myfinance/models/conf.py
from django.db import models

class Conf(models.Model):
    saldoInicial = models.DecimalField(null=True, max_digits=8, decimal_places=2)

myfinance/models/confModel.py
from django.db import models

class Conf(models.Model):
    saldoInicial = models.DecimalField(null=True, max_digits=8, decimal_places=2)

myfinance/models/despesa.py
from django.db import models

class Despesa(models.Model):
    CLASSIFICACAO_CHOICES = (
        ('AG', 'Água'),
        ('AL', 'Alimentação'),
        ('AG', 'Aluguel'),
        ('EN', 'Energia'),
        ('LA', 'Lazer'),
        ('OU', 'Outros'),
        ('TE', 'Telecomunicações'),
        ('TR', 'Transporte')
    )

    FORMA_PAGAMENTO_CHOICES = (
        ('B', 'Boleto'),
        ('C', 'Crédito'),
        ('D', 'Débito'),
        ('M', 'Dinheiro'),
        ('P', 'Depósito'),
        ('O', 'Outros')
    )
    
    SITUACAO_CHOICES = (
        ('PG', 'Pago'),
        ('AP', 'A pagar')
    )
    
    id = models.AutoField(primary_key=True)
    classificacao = models.CharField(max_length=2, choices=CLASSIFICACAO_CHOICES, default='OU')
    data_pagamento = models.DateField(null=True)
    data_vencimento = models.DateField(null=False)
    descricao = models.CharField(max_length=255)
    formaPagamento = models.CharField(max_length=1, choices=FORMA_PAGAMENTO_CHOICES, default='O')
    situacao = models.CharField(max_length=2, choices=SITUACAO_CHOICES, default='AP')
    valor = models.DecimalField(null=False, max_digits=8, decimal_places=2)

    def as_json(self):
        return dict(
            id = self.id
            , classificacao = self.classificacao
            , data_pagamento = self.data_pagamento
            , data_vencimento = self.data_vencimento
            , descricao = self.descricao
            , formaPagamento = self.formaPagamento
            , situacao = self.situacao
            , valor = self.valor
        )
    

myfinance/models/receita.py
from django.db import models

class Receita(models.Model):
    CLASSIFICACAO_CHOICES = (
        ('DT', 'Dívida de terceiros'),
        ('DO', 'Doação'),
        ('SA', 'Salário'),
        ('SP', 'Serviço prestado'),
        ('OU', 'Outros'),
        ('VE', 'Vendas')
    )

    FORMA_RECEBIMENTO_CHOICES = (
        ('B', 'Boleto'),
        ('C', 'Crédito'),
        ('D', 'Débito'),
        ('M', 'Dinheiro'),
        ('P', 'Depósito'),
        ('O', 'Outros')
    )
    
    SITUACAO_CHOICES = (
        ('PR', 'Recebido'),
        ('AR', 'A receber')
    )
    
    id = models.AutoField(primary_key=True)
    classificacao = models.CharField(max_length=2, choices=CLASSIFICACAO_CHOICES, default='OU')
    data_expectativa = models.DateField(null=False)
    data_recebimento = models.DateField(null=True)
    descricao = models.CharField(max_length=255)
    formaRecebimento = models.CharField(max_length=1, choices=FORMA_RECEBIMENTO_CHOICES, default='O')
    situacao = models.CharField(max_length=2, choices=SITUACAO_CHOICES, default='AR')
    valor = models.DecimalField(null=False, max_digits=8, decimal_places=2)


    def as_json(self):
        return dict(
            id = self.id
            , classificacao = self.classificacao
            , data_expectativa = self.data_expectativa
            , data_recebimento = self.data_recebimento
            , descricao = self.descricao
            , formaRecebimento = self.formaRecebimento
            , situacao = self.situacao
            , valor = self.valor
        )
    

myfinance/models/retornoRequest.py
class RetornoRequest:
    def __init__(self, eherro, message):
        self.eherro = eherro
        self.message = message

    def as_json(self):
        return dict(
            eherro = self.eherro
            , message = self.message
        )        

myfinance/models/retornoRequestModel.py
class RetornoRequest:
    def __init__(self, eherro, message):
        self.eherro = eherro
        self.message = message

    def as_json(self):
        return dict(
            eherro = self.eherro
            , message = self.message
        )        

myfinance/views.py
from django.shortcuts import render

# Create your views here.

myfinance/views/despesa.py
from django.views.decorators.http import require_http_methods
from datetime import date
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
import json

from ..models import Despesa, RetornoRequest
from ..utils import Utils

# GET: retorna a lista de despesas
# POST: cria no banco uma nova despesa
@require_http_methods(["GET", "POST"])   
@csrf_exempt
def despesa(request):
    if(request.method=="GET"):
        despesas = [ob.as_json() for ob in Despesa.objects.all()]
        return HttpResponse(json.dumps(despesas, default=Utils.converter), content_type="application/json")
    elif(request.method=="POST"):
        atualizaDespesa(request, 0)
        return JsonResponse(RetornoRequest(False, "Objeto criado com sucesso.").as_json())


# GET: retorna dados de uma despesa
# POST: atualiza no banco a despesa de ID = id_despesa
# DELETE: deleta do banco a despesa de ID = id_despesa
@require_http_methods(["GET", "POST", "DELETE"])  
@csrf_exempt
def despesaOp(request, id_despesa):
    despesa = None
    try:
        despesa = Despesa.objects.get(id=id_despesa)
    except ObjectDoesNotExist:
        return JsonResponse(RetornoRequest(True, "Objeto não encontrado.").as_json())

    if(request.method=="GET"):
        context = {}
        if(despesa):
            return JsonResponse(despesa.as_json())   

    elif(request.method=="POST"):
        if(despesa):
            atualizaDespesa(request, id_despesa)
            return JsonResponse(RetornoRequest(False, "Objeto atualizado com sucesso.").as_json())

    elif(request.method=="DELETE"):
        jsonReturn = RetornoRequest(True, "Não foi possível excluir o objeto.").as_json()
        if(despesa):
            despesa.delete()
            jsonReturn = RetornoRequest(False, "Objeto excluído com sucesso.").as_json()
        return JsonResponse(jsonReturn)

# atualiza as informações de uma despesa existente
def atualizaDespesa(request, id_despesa):
    body = json.loads(request.body.decode('utf-8'))
    dataPagamento = body['data_pagamento']

    if(dataPagamento == ""):
        dataPagamento = None

    despesa = Despesa(classificacao=body['classificacao'],
                      data_pagamento=dataPagamento,
                      data_vencimento=body['data_vencimento'],
                      descricao=body['descricao'],
                      formaPagamento=body['formaPagamento'],
                      situacao=body['situacao'],
                      valor=body['valor']
                    )

    if (id_despesa > 0):
        despesa.id = id_despesa

    despesa.save()

myfinance/views/despesaView.py
from django.views.decorators.http import require_http_methods
from datetime import date
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
import json

from ..models import Despesa, RetornoRequest
from ..utils import Utils

# GET: retorna a lista de despesas
# POST: cria no banco uma nova despesa
@require_http_methods(["GET", "POST"])   
@csrf_exempt
def despesa(request):
    if(request.method=="GET"):
        despesas = [ob.as_json() for ob in Despesa.objects.all()]
        return HttpResponse(json.dumps(despesas, default=Utils.converterParaListagem), content_type="application/json")
    elif(request.method=="POST"):
        atualizaDespesa(request, 0)
        return JsonResponse(RetornoRequest(False, "Objeto criado com sucesso.").as_json())


# GET: retorna dados de uma despesa
# POST: atualiza no banco a despesa de ID = id_despesa
# DELETE: deleta do banco a despesa de ID = id_despesa
@require_http_methods(["GET", "POST", "DELETE"])  
@csrf_exempt
def despesaOp(request, id_despesa):
    despesa = None
    try:
        despesa = Despesa.objects.get(id=id_despesa)
    except ObjectDoesNotExist:
        return JsonResponse(RetornoRequest(True, "Objeto não encontrado.").as_json())

    if(request.method=="GET"):
        context = {}
        if(despesa):
            return JsonResponse(despesa.as_json())   

    elif(request.method=="POST"):
        if(despesa):
            atualizaDespesa(request, id_despesa)
            return JsonResponse(RetornoRequest(False, "Objeto atualizado com sucesso.").as_json())

    elif(request.method=="DELETE"):
        jsonReturn = RetornoRequest(True, "Não foi possível excluir o objeto.").as_json()
        if(despesa):
            despesa.delete()
            jsonReturn = RetornoRequest(False, "Objeto excluído com sucesso.").as_json()
        return JsonResponse(jsonReturn)

# atualiza as informações de uma despesa existente
def atualizaDespesa(request, id_despesa):
    body = json.loads(request.body.decode('utf-8'))
    dataPagamento = body['data_pagamento']

    if(dataPagamento == "" or dataPagamento == []):
        dataPagamento = None

    despesa = Despesa(classificacao=body['classificacao'],
                      data_pagamento=dataPagamento,
                      data_vencimento=body['data_vencimento'],
                      descricao=body['descricao'],
                      formaPagamento=body['formaPagamento'],
                      situacao=body['situacao'],
                      valor=body['valor']
                    )

    if (id_despesa > 0):
        despesa.id = id_despesa

    despesa.save()

myfinance/views/loginView.py
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from datetime import datetime, timedelta
import jwt
import json

from ..models import RetornoRequest, User
from ..utils.utils import JWT_ALGORITHM, JWT_EXP_DELTA_SECONDS, JWT_SECRET

@require_http_methods(["POST"])   
@csrf_exempt
def login(request):
    body = json.loads(request.body.decode('utf-8'))

    user = User.objects.filter(email=body['email']).first()
    if user == None:
        return JsonResponse(RetornoRequest(True, "Usuário não localizado.").as_json())

    try:
        user.match_password(body['password'])
    except (User.DoesNotExist, User.PasswordDoesNotMatch):
        return JsonResponse(RetornoRequest(True, "Credenciais inválidas.").as_json())

    payload = {
        'user_id': user.id,
        'exp': datetime.utcnow() + timedelta(seconds=JWT_EXP_DELTA_SECONDS)
    }    
    jwt_token = jwt.encode(payload, JWT_SECRET, JWT_ALGORITHM)

    return JsonResponse({'eherro': False, 
                         'id': user.id,
                         'username': user.email,
                         'name': user.nome,
                         'token': jwt_token.decode('utf-8')})

myfinance/views/receita.py
from django.views.decorators.http import require_http_methods
from datetime import date
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
import json

from ..models import Receita, RetornoRequest
from ..utils import Utils

# GET: retorna a lista de receitas
# POST: cria no banco uma nova receita
@require_http_methods(["GET", "POST"])   
@csrf_exempt
def receita(request):
    if(request.method=="GET"):
        receitas = [ob.as_json() for ob in Receita.objects.all()]
        return HttpResponse(json.dumps(receitas, default=Utils.converter), content_type="application/json")
    elif(request.method=="POST"):
        atualizaReceita(request, 0)
        return JsonResponse(RetornoRequest(False, "Objeto criado com sucesso.").as_json())        
       
# GET: retorna dados de uma receita
# POST: atualiza no banco a receita de ID = id_receita
# DELETE: deleta do banco a receita de ID = id_receita
@require_http_methods(["GET", "POST", "DELETE"])  
@csrf_exempt
def receitaOp(request, id_receita):
    receita = None
    try:
        receita = Receita.objects.get(id=id_receita)
    except ObjectDoesNotExist:
        return JsonResponse(RetornoRequest(True, "Objeto não encontrado.").as_json())

    if(request.method=="GET"):
        context = {}
        if(receita):
            return JsonResponse(receita.as_json())   

    elif(request.method=="POST"):
        if(receita):
            atualizaReceita(request, id_receita)
            return JsonResponse(RetornoRequest(False, "Objeto atualizado com sucesso.").as_json())

    elif(request.method=="DELETE"):
        jsonReturn = RetornoRequest(True, "Não foi possível excluir o objeto.").as_json()
        if(receita):
            receita.delete()
            jsonReturn = RetornoRequest(False, "Objeto excluído com sucesso.").as_json()
        return JsonResponse(jsonReturn)

# atualiza as informações de uma receita existente
def atualizaReceita(request, id_receita):
    body = json.loads(request.body.decode('utf-8'))
    dataRecebimento = body['data_recebimento']

    if(dataRecebimento == ""):
        dataRecebimento = None

    receita = Receita(classificacao=body['classificacao'],
                      data_recebimento=dataRecebimento,
                      data_expectativa=body['data_expectativa'],
                      descricao=body['descricao'],
                      formaRecebimento=body['formaRecebimento'],
                      situacao=body['situacao'],
                      valor=body['valor']
                    )

    if (id_receita > 0):
        receita.id = id_receita

    receita.save()

myfinance/views/receitaView.py
from django.views.decorators.http import require_http_methods
from datetime import date
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
import json

from ..models import Receita, RetornoRequest
from ..utils import Utils

# GET: retorna a lista de receitas
# POST: cria no banco uma nova receita
@require_http_methods(["GET", "POST"])   
@csrf_exempt
def receita(request):
    if(request.method=="GET"):
        receitas = [ob.as_json() for ob in Receita.objects.all()]
        return HttpResponse(json.dumps(receitas, default=Utils.converterParaListagem), content_type="application/json")
    elif(request.method=="POST"):
        atualizaReceita(request, 0)
        return JsonResponse(RetornoRequest(False, "Objeto criado com sucesso.").as_json())        
       
# GET: retorna dados de uma receita
# POST: atualiza no banco a receita de ID = id_receita
# DELETE: deleta do banco a receita de ID = id_receita
@require_http_methods(["GET", "POST", "DELETE"])  
@csrf_exempt
def receitaOp(request, id_receita):
    receita = None
    try:
        receita = Receita.objects.get(id=id_receita)
    except ObjectDoesNotExist:
        return JsonResponse(RetornoRequest(True, "Objeto não encontrado.").as_json())

    if(request.method=="GET"):
        context = {}
        if(receita):
            return JsonResponse(receita.as_json())   

    elif(request.method=="POST"):
        if(receita):
            atualizaReceita(request, id_receita)
            return JsonResponse(RetornoRequest(False, "Objeto atualizado com sucesso.").as_json())

    elif(request.method=="DELETE"):
        jsonReturn = RetornoRequest(True, "Não foi possível excluir o objeto.").as_json()
        if(receita):
            receita.delete()
            jsonReturn = RetornoRequest(False, "Objeto excluído com sucesso.").as_json()
        return JsonResponse(jsonReturn)

# atualiza as informações de uma receita existente
def atualizaReceita(request, id_receita):
    body = json.loads(request.body.decode('utf-8'))
    dataRecebimento = body['data_recebimento']

    if(dataRecebimento == "" or dataRecebimento == []):
        dataRecebimento = None

    receita = Receita(classificacao=body['classificacao'],
                      data_recebimento=dataRecebimento,
                      data_expectativa=body['data_expectativa'],
                      descricao=body['descricao'],
                      formaRecebimento=body['formaRecebimento'],
                      situacao=body['situacao'],
                      valor=body['valor']
                    )

    if (id_receita > 0):
        receita.id = id_receita

    receita.save()

myfinance/templates/index.html
<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>API backend - Gerenciamento financeiro</title>
    </head>
    <body>
        <div class="container">
            <h1>API backend - Gerenciamento financeiro</h1>            
        </div>
    </body>
</html>

myfinance/templates/relatorioDespesas.html
<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <title>Relatório de contas pendentes</title>
    </head>
    <body>
        <div class="container">
            <h1>Gerenciamento financeiro</h1>
            <h6>Feito em Python</h6>

            <ul class="nav justify-content-center nav-pills">
                <li class="nav-item">
                    <a class="nav-link border" href="/"><h4>Fluxo de caixa</h4></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link border" href="/despesa/"><h4>Nova despesa</h4></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link border" href="/receita/"><h4>Nova receita</h4></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active border" href="/relatorio/despesas"><h4>Contas a pagar</h4></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link border" href="/relatorio/receitas"><h4>Contas a receber</h4></a>
                </li>
            </ul>

            <h4 class="mt-4">Relatório de contas pendentes</h4>
            <form action="/relatorio/despesas/filtro" method="post" class="mt-5 mb-5">
                <div class="form-row mt-2">
                    <label for="inputDate" class="col-sm-2 font-weight-bold">Data vencimento: </label>
                    <input type="date" class="form-control-sm col-sm-2" id="inputDate" name="data_filtro" value="{{dateMax}}" required>
                
                    <button type="submit" class="btn btn-dark btn-sm ml-2 col-sm-1">Filtrar</button>
                </div>
            </form>
            {% if despesas %}
                <button type="button" class="btn btn-dark mb-1 mt-1">
                    Quantidade <span class="badge badge-light">{{ despesas|length }}</span>
                </button>
                <table class="table table-bordered table-striped table-sm" id="tableRelatorio">
                    <thead>
                        <tr class="bg-dark text-white"> 
                            <th scope="col" style="width: 15%">Data de vencimento</th>
                            <th scope="col" style="width: 25%">Descrição</th>
                            <th scope="col" style="width: 15%">Classificação</th>
                            <th scope="col" style="width: 15%">Forma de pagamento</th>
                            <th scope="col" style="width: 10%">Valor (R$)</th>
                        </tr>
                    </thead>
                    <tbody class="table-light">
                        {% for despesa in despesas %}
                            <tr>
                                <td>{{despesa.data_vencimento}}</td>
                                <td>{{despesa.descricao}}</td>
                                <td>{{despesa.get_classificacao_display}}</td>
                                <td>{{despesa.get_formaPagamento_display}}</td>
                                <td>{{despesa.valor}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="d-flex justify-content-end">
                    <button type="button" class="btn btn-danger mb-1 mt-1">
                        Valor total a pagar <span class="badge badge-light">R$ {{ valorTotal }}</span>
                    </button>
                </div>
            {% else %}
                <div class="d-flex justify-content-center">
                    <h3>Não existem contas pendentes até a data {{dateMaxBr}}</h3>
                </div>
            {% endif %}  
        </div>
    </body>
</html>

myfinance/templates/relatorioReceitas.html
<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <title>Relatório de contas a receber</title>
    </head>
    <body>
        <div class="container">
            <h1>Gerenciamento financeiro</h1>
            <h6>Feito em Python</h6>

            <ul class="nav justify-content-center nav-pills">
                <li class="nav-item">
                    <a class="nav-link border" href="/"><h4>Fluxo de caixa</h4></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link border" href="/despesa/"><h4>Nova despesa</h4></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link border" href="/receita/"><h4>Nova receita</h4></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link border" href="/relatorio/despesas"><h4>Contas a pagar</h4></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active border" href="/relatorio/receitas"><h4>Contas a receber</h4></a>
                </li>
            </ul>

            <h4 class="mt-4">Relatório de contas a receber</h4>
            <form action="/relatorio/receitas/filtro" method="post" class="mt-5 mb-5">
                <div class="form-row mt-2">
                    <label for="inputDate" class="col-sm-2 font-weight-bold">Data expectativa: </label>
                    <input type="date" class="form-control-sm col-sm-2" id="inputDate" name="data_filtro" value="{{dateMax}}" required>
                
                    <button type="submit" class="btn btn-dark btn-sm ml-2 col-sm-1">Filtrar</button>
                </div>
            </form>
            {% if receitas %}
                <button type="button" class="btn btn-dark mb-1 mt-1">
                    Quantidade <span class="badge badge-light">{{ receitas|length }}</span>
                </button>
                <table class="table table-bordered table-striped table-sm" id="tableRelatorio">
                    <thead>
                        <tr class="bg-dark text-white"> 
                            <th scope="col" style="width: 15%">Data expectativa</th>
                            <th scope="col" style="width: 25%">Descrição</th>
                            <th scope="col" style="width: 15%">Classificação</th>
                            <th scope="col" style="width: 15%">Forma de recebimento</th>
                            <th scope="col" style="width: 10%">Valor (R$)</th>
                        </tr>
                    </thead>
                    <tbody class="table-light">
                        {% for receita in receitas %}
                            <tr>
                                <td>{{receita.data_expectativa}}</td>
                                <td>{{receita.descricao}}</td>
                                <td>{{receita.get_classificacao_display}}</td>
                                <td>{{receita.get_formaRecebimento_display}}</td>
                                <td>{{receita.valor}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="d-flex justify-content-end">
                    <button type="button" class="btn btn-success mb-1 mt-1">
                        Valor total a receber <span class="badge badge-light">R$ {{ valorTotal }}</span>
                    </button>
                </div>
            {% else %}
                <div class="d-flex justify-content-center">
                    <h3>Não existem contas a receber até a data {{dateMaxBr}}</h3>
                </div>
            {% endif %}  
        </div>
    </body>
</html>